"""Create product image table

Revision ID: 2348bf3c7566
Revises: 36167f5a2400
Create Date: 2026-09-30 16:19:21.020928

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2348bf3c7566"
down_revision: str | Sequence[str] | None = "36167f5a2400"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product_images",
        sa.Column(
            "product_image_id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("variant_id", sa.UUID(), nullable=False),
        sa.Column("image_url", sa.Text(), nullable=False),
        sa.Column("cloudinary_public_id", sa.VARCHAR(length=255), nullable=False),
        sa.Column("alt_text", sa.VARCHAR(length=255), nullable=False),
        sa.Column(
            "sort_order", sa.INTEGER(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "is_primary", sa.BOOLEAN(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "is_active", sa.BOOLEAN(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["variant_id"],
            ["variants.variant_id"],
        ),
        sa.PrimaryKeyConstraint("product_image_id"),
    )
    op.create_index(
        op.f("ix_product_images_variant_id"),
        "product_images",
        ["variant_id"],
        unique=False,
    )
    op.create_index(
        "uq_product_images_one_primary_per_variant",
        "product_images",
        ["variant_id"],
        unique=True,
        postgresql_where=sa.text("is_primary IS TRUE"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_product_images_one_primary_per_variant",
        table_name="product_images",
        postgresql_where=sa.text("is_primary IS TRUE"),
    )
    op.drop_index(op.f("ix_product_images_variant_id"), table_name="product_images")
    op.drop_table("product_images")
    # ### end Alembic commands ###
